[package]
name = "slint-launch"
description = "Tauri-free mirror of crates/launch for the Slint app"
version = "0.0.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
slint-shared.workspace = true
slint-config.workspace = true
slint-account.workspace = true
slint-folder.workspace = true
slint-instance.workspace = true
slint-install.workspace = true
slint-java-runtime.workspace = true
slint-platform.workspace = true
slint-version.workspace = true
slint-download.workspace = true
slint-statistics.workspace = true

log.workspace = true
num_cpus.workspace = true
regex.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
thiserror.workspace = true
tokio.workspace = true
uuid.workspace = true
zip.workspace = true
