[package]
name = "install"
description = "Minecraft and loader installation"
version = "0.0.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
config.workspace = true
folder.workspace = true
instance.workspace = true
download.workspace = true
platform.workspace = true
version.workspace = true
java-runtime.workspace = true
shared.workspace = true

log.workspace = true
once_cell.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokio.workspace = true
url.workspace = true
uuid.workspace = true
zip.workspace = true
