[package]
name = "beat_this"
version = "0.0.0"
authors = ["Broken-Deer"]

edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
shared.workspace = true
folder.workspace = true
download.workspace = true

tauri.workspace = true
reqwest.workspace = true
async-fs.workspace = true
libloader.workspace = true
thiserror.workspace = true
serde_with.workspace = true
serde.workspace = true
sha2.workspace = true
futures.workspace = true
serde_json.workspace = true
