name-template: "Conic Launcher v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - type: "pre-exclude"
    when:
      labels:
        - "ci"
        - "chore"
        - "documentation"
        - "refactor"
        - "test"
        - "style"
        - "release"
  - title: "✨ Features"
    when:
      labels:
        - "feature"
        - "enhancement"
  - title: "🐛 Bug Fixes"
    when:
      labels:
        - "fix"
        - "bugfix"
        - "bug"
  - title: "🚀 Performance"
    when:
      labels:
        - "performance"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&'
template: |
  $CHANGES
