name-template: "Conic Launcher v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "✨ Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "🚀 Performance"
    labels:
      - "performance"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&'
exclude-labels:
  - "ci"
  - "chore"
  - "documentation"
  - "refactor"
  - "test"
  - "style"
template: |
  $CHANGES
