name-template: "Conic Launcher v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - type: "pre-exclude"
    when:
      labels:
        - "ci"
        - "chore"
        - "documentation"
        - "refactor"
        - "test"
        - "style"
        - "release"
  - title: "Enhancements"
    when:
      labels:
        - "feature"
        - "enhancement"
        - "performance"
  - title: "Fixed"
    when:
      labels:
        - "fix"
        - "bugfix"
        - "bug"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&'
replacers:
  - target: change-title
    search: '/^(?:feat|fix|chore|perf)(?:\([^)]*\))?!?: (.*)$/'
    replace: '\u$1'
template: |
  $CHANGES
