[package]
name = "music"
version = "0.0.0"
authors = ["OakChaser"]

edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
shared.workspace = true
folder.workspace = true

tauri.workspace = true
async-fs.workspace = true
thiserror.workspace = true
serde_with.workspace = true
serde.workspace = true
log.workspace = true
