// Conic Launcher
// Copyright 2022-2026 ConicMC developers. All rights reserved.
// SPDX-License-Identifier: GPL-3.0-only

use tauri_build::InlinedPlugin;

fn main() {
    let attributes = tauri_build::Attributes::new()
        .plugin(
            "config",
            InlinedPlugin::new().commands(&[
                "cmd_load_config_file",
                "cmd_get_default_config",
                "cmd_save_config",
                "cmd_get_system_language",
            ]),
        )
        .plugin(
            "account",
            InlinedPlugin::new().commands(&[
                "cmd_list_accounts",
                "cmd_save_skin",
                "cmd_microsoft_get_account",
                "cmd_microsoft_delete_account",
                "cmd_microsoft_add_account",
                "cmd_microsoft_update_account",
                "cmd_microsoft_redeem_access_token",
                "cmd_microsoft_access_token_auth_flow",
                "cmd_microsoft_refresh_account",
                "cmd_microsoft_request_device_code",
                "cmd_microsoft_poll_device_code",
                "cmd_offline_add_account",
                "cmd_offline_delete_account",
                "cmd_offline_update_account",
                "cmd_offline_get_account",
                "cmd_yggdrasil_get_server_info",
                "cmd_yggdrasil_authenticate_account",
                "cmd_yggdrasil_validate_account",
                "cmd_yggdrasil_refresh_account",
                "cmd_yggdrasil_invalidate_account",
                "cmd_yggdrasil_get_profile",
                "cmd_yggdrasil_get_profiles",
                "cmd_yggdrasil_add_account",
                "cmd_yggdrasil_delete_account",
                "cmd_yggdrasil_get_account",
                "cmd_yggdrasil_list_accounts",
                "cmd_yggdrasil_update_account",
            ]),
        )
        .plugin(
            "download",
            InlinedPlugin::new().commands(&["cmd_spawn_download_task", "cmd_cancel_download_task"]),
        )
        .plugin(
            "content",
            InlinedPlugin::new().commands(&[
                "cmd_get_all_levels",
                "cmd_get_save_icon",
                "cmd_get_save_path",
                "cmd_delete_save",
                "cmd_get_all_datapacks",
                "cmd_get_all_resourcepacks",
                "cmd_render_world_map",
                "cmd_list_screenshots",
                "cmd_parse_mods",
            ]),
        )
        .plugin(
            "install",
            InlinedPlugin::new().commands(&[
                "cmd_get_minecraft_version_list",
                "cmd_get_fabric_version_list",
                "cmd_get_quilt_version_list",
                "cmd_get_forge_version_list",
                "cmd_get_neoforge_version_list",
                "cmd_spawn_install_task",
                "cmd_cancel_install_task",
            ]),
        )
        .plugin(
            "instance",
            InlinedPlugin::new().commands(&[
                "cmd_create_instance",
                "cmd_list_instances",
                "cmd_get_instance_by_id",
                "cmd_update_instance",
                "cmd_delete_instance",
                "cmd_add_background_file",
                "cmd_get_background_path",
                "cmd_calculate_playtime",
            ]),
        )
        .plugin(
            "launch",
            InlinedPlugin::new().commands(&["cmd_spawn_launch_task", "cmd_cancel_launch_task"]),
        )
        .plugin(
            "multiplayer",
            InlinedPlugin::new().commands(&[
                "cmd_spawn_download_library_task",
                "cmd_cancel_download_library_task",
                "cmd_check_library_valid",
                "cmd_create_room",
                "cmd_join_room",
                "cmd_leave_room",
                "cmd_get_session_state",
                "cmd_query_peers",
                "cmd_recent_logs",
                "cmd_room_code_is_valid",
                "cmd_version",
                "cmd_configure",
            ]),
        )
        .plugin(
            "modrinth",
            InlinedPlugin::new().commands(&[
                "cmd_search_projects",
                "cmd_get_project",
                "cmd_get_multiple_projects",
                "cmd_get_all_dependencies",
                "cmd_list_project_versions",
                "cmd_spawn_download_mod_task",
                "cmd_cancel_download_task",
            ]),
        )
        .plugin(
            "music",
            InlinedPlugin::new().commands(&["cmd_list_music_files"]),
        )
        .plugin(
            "curseforge",
            InlinedPlugin::new().commands(&[
                "cmd_search_mods",
                "cmd_get_mod",
                "cmd_get_mods",
                "cmd_get_featured_mods",
                "cmd_get_mod_description",
                "cmd_get_mod_files",
                "cmd_get_mod_file",
                "cmd_get_files",
                "cmd_get_mod_file_changelog",
                "cmd_get_mod_file_download_url",
            ]),
        )
        .plugin(
            "platform",
            InlinedPlugin::new().commands(&["cmd_get_platform_info"]),
        )
        .plugin(
            "folder",
            InlinedPlugin::new().commands(&["cmd_get_data_location", "cmd_get_instance_root"]),
        )
        .plugin(
            "java-runtime",
            InlinedPlugin::new().commands(&["cmd_scan_java"]),
        )
        .plugin(
            "statistics",
            InlinedPlugin::new().commands(&["cmd_get_statistics", "cmd_get_statistics_by_profile"]),
        )
        .plugin(
            "update",
            InlinedPlugin::new().commands(&[
                "cmd_check_update",
                "cmd_download_and_install_update",
                "cmd_cancel_update",
            ]),
        )
        .plugin(
            "beat",
            InlinedPlugin::new().commands(&[
                "cmd_spawn_download_library_task",
                "cmd_cancel_download_library_task",
                "cmd_parse_audio_file",
            ]),
        );
    tauri_build::try_build(attributes).unwrap();
}
