[package]
name = "multiplayer"
description = "Tauri-free mirror of crates/multiplayer for the Slint app"
version = "0.0.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
shared.workspace = true
folder.workspace = true
download.workspace = true

reqwest.workspace = true
tokio.workspace = true
libloader.workspace = true
thiserror.workspace = true
serde_with.workspace = true
serde.workspace = true
sha2.workspace = true
futures.workspace = true
serde_json.workspace = true
log.workspace = true
