[package]
name = "modrinth"
description = "Modrinth API client"
version = "0.0.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
shared.workspace = true
download.workspace = true

log.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
thiserror.workspace = true
tokio.workspace = true
url.workspace = true
