// Conic Launcher
// Copyright 2022-2026 ConicMC developers. All rights reserved.
// SPDX-License-Identifier: GPL-3.0-only

import { SettingGroup } from "../../components/settings/setting-group.slint";
import { SettingItem } from "../../components/settings/setting-item.slint";
import { Switch } from "../../components/controls/switch.slint";
import { SliderBar } from "../../components/controls/slider-bar.slint";
import { AppConfig } from "../../globals/settings.slint";

export component SettingsAudio inherits VerticalLayout {
    width: 100%;
    padding-left: 8px;
    padding-right: 8px;
    spacing: 16px;
    alignment: start;

    SettingGroup {
        title: @tr("Background music");

        SettingItem {
            group-first: true;
            title: @tr("Enable background music");
            description: @tr("Play background music in the launcher.");

            Switch {
                checked <=> AppConfig.music-enabled;
                toggled => { AppConfig.changed(); }
            }
        }

        SettingItem {
            title: @tr("Resume on start");
            description: @tr("Resume the last track and its progress when the application starts.");

            Switch {
                checked <=> AppConfig.resume-on-startup;
                toggled => { AppConfig.changed(); }
            }
        }

        SettingItem {
            title: @tr("Audio visualizer");
            description: @tr("Show audio visualization at the bottom of the game page.");

            Switch {
                checked <=> AppConfig.show-visualizer;
                toggled => { AppConfig.changed(); }
            }
        }

        SettingItem {
            title: @tr("Pause on game launch");
            description: @tr("Automatically pause background music when the game finishes launching.");

            Switch {
                checked <=> AppConfig.pause-on-launch;
                toggled => { AppConfig.changed(); }
            }
        }

        SettingItem {
            group-last: true;
            title: @tr("Open music folder");
            description: @tr("Place the music you want to play in this folder.");
            navigable: true;
            clicked => { AppConfig.open-path("music"); }
        }
    }

    SettingGroup {
        title: @tr("Volume");

        SettingItem {
            group-first: true;
            title: @tr("Master volume");
            description: AppConfig.main-volume + "%";

            SliderBar {
                max: 100;
                min: 0;
                step: 5;
                value <=> AppConfig.main-volume;
                edited => { AppConfig.changed(); }
            }
        }

        SettingItem {
            group-last: true;
            title: @tr("Master volume (window inactive)");
            description: AppConfig.background-volume + "%";

            SliderBar {
                max: 100;
                min: 0;
                step: 5;
                value <=> AppConfig.background-volume;
                edited => { AppConfig.changed(); }
            }
        }
    }
}
