#!/usr/bin/env python3
# Conic Launcher
# Copyright 2022-2026 ConicMC developers. All rights reserved.
# SPDX-License-Identifier: GPL-3.0-only

"""Check that every icon name a `.slint` file asks for actually exists.

`ui/icons.slint` is generated by `app/build.rs` on every build, so its
contents cannot drift from the SVGs -- that was the whole point. What the
generator *cannot* see is a name that does not exist: `Icons.stroke-commands()`
returns `""` for one, `AppIcon` draws an empty `Path`, and the icon is simply
missing with nothing logged. This is the one failure mode left, so it is worth
a check.

The names come from three places, all of them string literals in the tree:

  * `AppIcon { name: "..." }`      -- the 58 call sites
  * `icon: "..."`                  -- a `SettingItem` / `ContentCard` / model row
                                       property, bound to an `AppIcon` further down
  * `marker-icon: { ... }`         -- `markdown-body.slint`, handed to the markdown crate

Run:  python3 tools/check-icon-names.py

Exit code is 1 when a name has no SVG, so it can be dropped into CI as-is.
"""

from __future__ import annotations

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
UI = ROOT / "app/ui"
CRATES = ROOT / "crates"

# The SVGs the generator reads, mirroring `ICON_SOURCES` in `app/build.rs`.
# The two brand marks are the only SVGs taken from `assets/images/` -- the rest
# of that directory is artwork a `.slint` file draws by `@image-url`, which is
# never an icon name.
ICON_FILES = sorted(
    [*(ROOT / "app/ui/assets/icons").glob("*.svg"),
     ROOT / "app/ui/assets/images/modrinth.svg",
     ROOT / "app/ui/assets/images/curseforge.svg"],
    key=lambda path: path.stem,
)
# Names the app draws itself rather than reading from an SVG, so a literal of the
# same name in a binding is not a missing icon. These are the window-control
# glyphs in `title-bar.slint` and the placeholder artwork in
# `views/todo-placeholder.slint`.
DRAWN_IN_CODE = {"minimize-icon", "maximize-icon", "close-icon", "cubes-icon"}


def slint_files() -> list[pathlib.Path]:
    return [*sorted(UI.rglob("*.slint")), *sorted(CRATES.rglob("*.slint"))]


def asked_names(path: pathlib.Path) -> list[tuple[int, str]]:
    """`(line, name)` for every icon name this file asks for by literal."""
    source = path.read_text()
    found: list[tuple[int, str]] = []
    lines = source.splitlines()
    for number, line in enumerate(lines, start=1):
        # `icon: "folder"` -- a `SettingItem` / `ContentCard` / model row property
        # that an `AppIcon` further down is bound to. The property name is fixed
        # (`icon`), so no disambiguation is needed; the hand-drawn `cubes-icon`
        # is excluded by requiring the bare word.
        for match in re.finditer(r'(?<![\w-])icon:\s*"([^"]+)"', line):
            found.append((number, match.group(1)))

    # `AppIcon { name: "folder" }`. The `name:` has to belong to an `AppIcon`
    # rather than to one of the app's own properties (`cubes-icon: "M290.8 ..."`
    # is drawn in code and has no SVG), so an `AppIcon {` has to open the block
    # the `name:` sits in -- which it does on the line above, so this is a
    # window rather than a single line.
    for match in re.finditer(r'\bAppIcon\s*\{([^{}]*?)\}', source, re.S):
        block = match.group(1)
        for name in re.finditer(r'(?<![\w-])name:\s*"([^"]+)"', block):
            found.append((source.count("\n", 0, match.start() + name.start()) + 2, name.group(1)))
    return sorted(found)


def main() -> int:
    known = {path.stem for path in ICON_FILES}
    missing: list[tuple[pathlib.Path, int, str]] = []

    for path in slint_files():
        # The generated table is itself full of `if name == "..."`, and is not
        # in the tree at all on a fresh clone.
        if path.name == "icons.slint":
            continue
        for number, name in asked_names(path):
            if name in known or name in DRAWN_IN_CODE:
                continue
            missing.append((path, number, name))

    for path, number, name in missing:
        print(f"{path.relative_to(ROOT)}:{number}: no icon named {name!r}")
    if missing:
        print(
            f"\n{len(missing)} icon name(s) have no SVG. Add the file to "
            f"`app/ui/assets/icons/`, or fix the spelling."
        )
        return 1
    print(f"every icon name resolves to one of the {len(known)} SVGs")
    return 0


if __name__ == "__main__":
    sys.exit(main())
