// Conic Launcher
// Copyright 2022-2026 ConicMC developers. All rights reserved.
// SPDX-License-Identifier: GPL-3.0-only

import { AccountItem } from "game.slint";

export struct DropdownOption {
    key: string,
    label: string,
    icon: string,
}

export global Dropdown {
    in-out property <bool> open: false;
    in-out property <[DropdownOption]> options: [];
    in-out property <[AccountItem]> accounts: [];
    in-out property <bool> account-mode: false;
    in-out property <string> current: "";
    in-out property <string> owner: "";

    in-out property <length> anchor-x: 0px;
    in-out property <length> anchor-y: 0px;
    in-out property <length> anchor-width: 240px;
    in-out property <bool> expand-upwards: false;

    in-out property <string> chosen: "";
    in-out property <string> choose-owner: "";
    in-out property <int> choose-serial: 0;
}
