name: Check Rust

on:
  push:
    branches: ["dev"]
    paths:
      - ".github/workflows/check-rust.yml"
      - "crates/**"
      - "app/**"
      - "Cargo.toml"
      - "Cargo.lock"
  pull_request:
    branches: ["dev"]
    paths:
      - ".github/workflows/check-rust.yml"
      - "crates/**"
      - "app/**"
      - "Cargo.toml"
      - "Cargo.lock"
env:
  RUST_BACKTRACE: 1
  CARGO_PROFILE_DEV_DEBUG: 0 # This would add unnecessary bloat to the target folder, decreasing cache efficiency.

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  clippy-and-fmt:
    strategy:
      matrix:
        include:
          - platform: "ubuntu-22.04"
          - platform: "ubuntu-22.04-arm"
          - platform: "macos-15"
          - platform: "macos-15-intel"
          - platform: "windows-latest"
          - platform: "windows-11-arm"
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v7

      - name: install dependencies
        if: startsWith(matrix.platform, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            pkg-config libfontconfig1-dev libasound2-dev libudev-dev

      - name: install Rust stable with clippy
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - uses: Swatinem/rust-cache@v2
      
      - name: Run cargo fmt
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy --manifest-path ./Cargo.toml --all-targets -- -D warnings

  test:
    strategy:
      matrix:
        include:
          - platform: "ubuntu-22.04"
          - platform: "ubuntu-22.04-arm"
          - platform: "macos-15"
          - platform: "macos-15-intel"
          - platform: "windows-latest"
          - platform: "windows-11-arm"
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v7

      - name: install dependencies
        if: startsWith(matrix.platform, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            pkg-config libfontconfig1-dev libasound2-dev libudev-dev

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - name: Run cargo test
        run: cargo test --all --verbose --all-targets
